[theme]
# Primary accent color for your app
primaryColor="#FF4B4B"
# Background color for the content
backgroundColor="#FFFFFF"
# Background color for the sidebar and other components
secondaryBackgroundColor="#F0F2F6"
# Color of the text
textColor="#303030"

[server]
# Set this to true to automatically open a browser tab when the server starts
runOnSave = true